MinPro334_GroupA/MinPro334_GroupA/Controllers/BankController.cs
using Microsoft.AspNetCore.Mvc;

using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class BankController : Controller
    {
        private BankService bankService;
        private int IdUser = 1;

        public BankController(BankService _bankService)
        {
            bankService = _bankService;
        }


        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<MBank> data = await bankService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }
            return View(PaginatedList<MBank>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 5));
        }

        public async Task<IActionResult> Create()
        {
            return PartialView();
        }

        public async Task<JsonResult> CheckBankIsExist(string name, long id)
        {
            bool isExist = await bankService.CheckBankByName(name, id);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMMBank dataParam)
        {
            VMResponse respon = await bankService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(long id)
        {
            VMMBank data = await bankService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMMBank dataParam)
        {
            VMResponse respon = await bankService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMMBank data = await bankService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await bankService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<JsonResult> CheckByName(string name)
        {
            bool isExist = await bankService.CheckByName(name);
            return Json(isExist);
        }

        public async Task<JsonResult> CheckByCode(string vacode)
        {
            bool isExist = await bankService.CheckByCode(vacode);
            return Json(isExist);
        }

        public async Task<JsonResult> CheckNameCodeIsExist(string name, string vacode)
        {
            bool isExist = await bankService.CheckNameCode(name, vacode);
            return Json(isExist);
        }





    }
}

MinPro334_GroupA/MinPro334_GroupA/Controllers/CaraPembayaranController.cs
using Microsoft.AspNetCore.Mvc;
using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class CaraPembayaranController : Controller
    {
        private CaraPembayaranService caraPembayaranService;
        private int IdUser = 1;

        public CaraPembayaranController(CaraPembayaranService _caraPembayaranService)
        {
            caraPembayaranService = _caraPembayaranService;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<MPaymentMethod> data = await caraPembayaranService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }
            return View(PaginatedList<MPaymentMethod>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 5));
        }

        public async Task<IActionResult> Create()
        {
            return PartialView();
        }

        public async Task<JsonResult> CheckNameIsExist(string name)
        {
            bool isExist = await caraPembayaranService.CheckPaymentMethodByName(name);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMMPaymentMethod dataParam)
        {
            VMResponse respon = await caraPembayaranService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(long id)
        {
            VMMPaymentMethod data = await caraPembayaranService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMMPaymentMethod dataParam)
        {
            VMResponse respon = await caraPembayaranService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMMPaymentMethod data = await caraPembayaranService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await caraPembayaranService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


    }
}

MinPro334_GroupA/MinPro334_GroupA/Views/Shared/_Header.cshtml
      <!--  Header Start -->
<header class="app-header">
    <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                    <i class="ti ti-menu-2"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                    <i class="ti ti-bell-ringing"></i>
                    <div class="notification bg-primary rounded-circle"></div>
                </a>
            </li>
        </ul>
        <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">

                <a id="btn_menubank" class="btn btn-primary" asp-controller="CaraPembayaran" asp-action="Index">Cara Pembayaran</a>
                <a id="btn_menubank" class="btn btn-primary" asp-controller="Bank" asp-action="Index">Menu Bank</a>

                <button id="btn_lupaPassword" class="btn btn-primary">Lupa Password</button>
                <button id="btn_daftar" class="btn btn-primary">Daftar</button>

                <a href="https://adminmart.com/product/modernize-free-bootstrap-admin-dashboard/" target="_blank" class="btn btn-primary">Download Free</a>
                <li class="nav-item dropdown">
                    <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="~/Modernize-1.0.0/src/assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                    </a>
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                        <div class="message-body">
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-user fs-6"></i>
                                <p class="mb-0 fs-3">My Profile</p>
                            </a>
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-mail fs-6"></i>
                                <p class="mb-0 fs-3">My Account</p>
                            </a>
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-list-check fs-6"></i>
                                <p class="mb-0 fs-3">My Task</p>
                            </a>
                            <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--  Header End -->

<script>
    $("#btn_daftar").click(function(){
        $("#modal_body").empty()
        $("#modal_body").load("Daftar/Register")

        $("#modal_judul").empty()
        $("#modal_judul").text("Daftar")

        $("#my_modal").modal("show")
        // $(".modal-dialog").addClass("modal-xl")
        // $(".modal-dialog").removeClass("modal-xl")
    })

    $("#btn_lupaPassword").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("Daftar/LupaPassword")

        $("#modal_judul").empty()
        $("#modal_judul").text("Lupa Password")

        $("#my_modal").modal("show")
        // $(".modal-dialog").addClass("modal-xl")
        // $(".modal-dialog").removeClass("modal-xl")
    })



</script>

MinPro334_GroupA/MinPro334_GroupA/Views/Shared/_Layout.cshtml
@{
    var modal_title= "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MinPro334_GroupA</title>

    <script src="~/Modernize-1.0.0/src/assets/libs/jquery/dist/jquery.min.js"></script> 
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MinPro334_GroupA.styles.css" asp-append-version="true" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modernize Free</title>
    <link rel="shortcut icon" type="image/png" href="~/Modernize-1.0.0/src/assets/images/logos/favicon.png" />
    <link rel="stylesheet" href="~/Modernize-1.0.0/src/assets/css/styles.min.css" />

    <!-- TOASTR-->
    <script src="~/Modernize-1.0.0/plugins/toastr/toastr.min.js"></script>"
    <link rel="stylesheet" href="~/Modernize-1.0.0/plugins/toastr/toastr.min.css">

    <!-- Sweet Alert-->
    <script src="~/Modernize-1.0.0/plugins/sweetalert2/sweetalert2.js"></script>




    

</head>
<body>
   
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <partial name="_Sidebar" />
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <partial name="_Header" />
            <div class="container-fluid">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>

  
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MiniProjectGroupA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="my_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal_judul" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header rounded-top" style="background-color: lightsteelblue">
                    <h1 class="modal-title fs-5" id="modal_judul">@modal_title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body rounded" style="background-color: aliceblue" id="modal_body">
                </div>
            </div>
        </div>
    </div>

    <!-- Loader modal -->
    <div class="modal fade" id="modal_load">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center" id="modal_load_body">
                    <div class="d-flex align-items-center">
                        <strong id="loader_status_name"></strong>
                        <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
*@
    
    <script src="~/Modernize-1.0.0/src/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/js/sidebarmenu.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/js/app.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/Modernize-1.0.0/src/assets/js/dashboard.js"></script>
</body>
</html>

@*<script>
    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-center",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>
*@

MinPro334_GroupA/MinPro334_GroupA/Views/Shared/_Sidebar.cshtml
    <!-- Sidebar Start -->
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
            <a href="./index.html" class="text-nowrap logo-img">
                <img src="~/Modernize-1.0.0/src/assets/images/logos/dark-logo.svg" width="180" alt="" />
            </a>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                <i class="ti ti-x fs-8"></i>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Home</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./index.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-layout-dashboard"></i>
                        </span>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">UI COMPONENTS</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./ui-buttons.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-article"></i>
                        </span>
                        <span class="hide-menu">Buttons</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./ui-alerts.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-alert-circle"></i>
                        </span>
                        <span class="hide-menu">Alerts</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./ui-card.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-cards"></i>
                        </span>
                        <span class="hide-menu">Card</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./ui-forms.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-file-description"></i>
                        </span>
                        <span class="hide-menu">Forms</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./ui-typography.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-typography"></i>
                        </span>
                        <span class="hide-menu">Typography</span>
                    </a>
                </li>
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">AUTH</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link"  aria-expanded="false">
                        <span>
                            <i class="ti ti-login"></i>
                        </span>
                        <span class="hide-menu">Login</span>
                    </a>
                </li>

               @* Modif By Ali Irvan*@
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Daftar" asp-action="Register" aria-expanded="false">
                        <span>
                            <i class="ti ti-user-plus"></i>
                        </span>
                        <span class="hide-menu">Register</span>
                    </a>
                </li>
                @*End Mod*@
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">EXTRA</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="./icon-tabler.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-mood-happy"></i>
                        </span>
                        <span class="hide-menu">Icons</span>
                    </a>
                </li>

                @* START MOD BY ALI*@

                <li class="sidebar-item">
                    <a asp-controller="Daftar" asp-action="Register" class="sidebar-link" aria-expanded="false">
                        <span>
                            <i class="ti ti-mood-happy"></i>
                        </span>
                        <span class="hide-menu">Daftar</span>
                    </a>
                </li>

                @* START MOD BY ALI*@

                <li class="sidebar-item">
                    <a class="sidebar-link" href="./sample-page.html" aria-expanded="false">
                        <span>
                            <i class="ti ti-aperture"></i>
                        </span>
                        <span class="hide-menu">Sample Page</span>
                    </a>
                </li>
            </ul>
            <div class="unlimited-access hide-menu bg-light-primary position-relative mb-7 mt-5 rounded">
                <div class="d-flex">
                    <div class="unlimited-access-title me-3">
                        <h6 class="fw-semibold fs-4 mb-6 text-dark w-85">Upgrade to pro</h6>
                        <a href="https://adminmart.com/product/modernize-bootstrap-5-admin-template/" target="_blank" class="btn btn-primary fs-2 fw-semibold lh-sm">Buy Pro</a>
                    </div>
                    <div class="unlimited-access-img">
                        <img src="~/Modernize-1.0.0/src/assets/images/backgrounds/rocket.png" alt="" class="img-fluid">
                    </div>
                </div>
            </div>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!--  Sidebar End -->